### ISSUE TITLE
[BUG] Selectable Item in a card will be rendered wrong

### ISSUE THREAD

**Issue by bduiku** [kirbydesign/designsystem#1052]
**Describe the bug**

**To Reproduce**

If a kirby-card includes a kirby-item and the item is selectable or includes a kirby-toggle then the kirby-card will be sqaure in safari.

**Kirby version**
- [e.g. 1.1.10]

**Expected behavior**

**Please complete the following information:**
- Browser [Safari, version 13]

**Additional context**

## Tasks:
- [x] Move issue from "Ready to do" -> "in progress" on our [project board](https://github.com/kirbydesign/designsystem/projects/1)
- [x] Create Fix Branch
- [x] Create test reproducing the error
- [x] Fix
- [x] If relevant [Update Examples and Showcase](https://cookbook.kirby.design/home/showcase/button)
- [x] Push commits to GitHub
- [x] Open a pull request (remember to add `closes #issueno` to the description) and ask @kirbydesign/kirby-guild for review
- [ ] Merge to master and delete branch
![Skærmbillede 2020-05-27 kl  10 28 54](https://user-images.githubusercontent.com/60474339/82996201-ec1f2980-a004-11ea-9dd5-185355baa8c9.png)

**Comment by bommariusser** [comment]
does this also fix this issue? @bduiku 
![Skærmbillede 2020-05-29 kl  07 40 57](https://user-images.githubusercontent.com/49033002/83226219-c0757e00-a181-11ea-8e15-5cae76785e18.png)
