### ISSUE TITLE
[Theme] Refactor/Update of Page Header

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#1155]
Collection of tasks to enhance the Page Header Toolbar.

TO DO list:

- [x] Investigate the structure of currrent header (Page - Header - Toolbar - back btn - btn's)
- [x] #2073
- [x] Header/toolbar title bold (#1455)
- [x] Enable option for subtitle on page (#811)
- [x] Dropshadow on header/toolbar (in Scroll state) (#2040)
- [x] #1981
- [x] #2219 
- [x] #2074
- [x] Check all styles and size of header/toolbar
- [x] Make it possible to trigger moving of content from the page area to the toolbar in various steps (added by @MadsBuchmann)
- [x] #2493 
- [ ] Make and update issues for the above mentioned tasks

**Describe the solution you'd like**

![Header : toolbar : Page](https://user-images.githubusercontent.com/71710012/146207462-d8620c32-db99-435b-81c4-da8bf77308cf.png)

https://zpl.io/bzz03KM
https://zpl.io/aXRgj8M

**Comment by henrikvoetmand** [comment]
Change in requirements and design for the Page header.
Task list should be evaluated:
![Issue - screens](https://user-images.githubusercontent.com/71710012/144215542-26c990c1-5dd7-4083-8418-1c57242e03c3.png)

**Comment by MadsBuchmann** [comment]
I've taken the liberty of converting "Animation of btn's and titles on scroll" to an issue in order to be able to refer to it in #811
