### ISSUE TITLE
[BUG] Kirby list swipe actions not working for Samsung Galaxy S[x]

### ISSUE THREAD

**Issue by lydemann** [kirbydesign/designsystem#1166]
**Describe the bug**
Kirby list swipe actions not working for Samsung Galaxy S[x] (bug confirmed on S8,S9,S10).
This is due to Samsung Galaxy returning `false` for media query `(hover: none)` even though you cannot hover on the device.

**To Reproduce**

1. Go to List - Swipe
2. See you can't swipe with Samsung Galaxy S[x]

**Kirby version**
- 1.2.86

**Expected behavior**
Swipe should be enabled for Samsung Galaxy S[x].

**Screenshots**

**Please complete the following information:**
- OS: Android
- Browser: Chrome
- Browser version: ??

**Additional context**

## Tasks:
- [ ] Move issue from "Ready to do" -> "in progress" on our [project board](https://github.com/kirbydesign/designsystem/projects/1)
- [ ] Create Fix Branch
- [ ] Create test reproducing the error
- [x] Fix
- [ ] If relevant [Update Examples and Showcase](https://cookbook.kirby.design/home/showcase/button)
- [ ] Push commits to GitHub
- [ ] Open a pull request (remember to add `closes #issueno` to the description) and ask @kirbydesign/kirby-guild for review
- [ ] Merge to master and delete branch

### Tech Refinement:
- [x] Add `$is-touch-device-query: '(pointer: coarse) and (hover: none)'` to `libs\designsystem\src\lib\scss\base\_variables.scss`
- [x] Add `static isTouchDeviceQuery()` to `libs\designsystem\src\lib\helpers\design-token-helper.ts` and return `styles.isTouchDeviceQuery` (auto-generated through `npm run transpile:sass-to-ts`)
- [ ] Use an approach similiar to [Ionic](https://github.com/ionic-team/ionic-framework/blob/4af54a2fea5d9cef843b1ebce849fb4a5c206f0b/core/src/utils/platform.ts#L19) to add a css-class to the html-element, e.g. named "is-touch" or "touch-device" or similiar...
[ ] Consider using `APP_INITIALIZER` provided in KirbyModule to initialize the css-class
- [ ] Apply css-class using `window.matchMedia(DesignTokenHelper.isTouchDeviceQuery())` + a whitelist check for Samsung Galaxy S[x] through browsersniffing (`navigator.userAgent` + [this list](https://deviceatlas.com/blog/list-of-user-agent-strings#android))
- [ ] Apply list.swipeEnabled if `window.matchMedia(DesignTokenHelper.isTouchDeviceQuery()` and/or html-element hasClass('is-touch')
- [ ] Consider creating a utility function `isTouchDevice` that checks for the above
- [ ] Consider patching `hover()`, `focus()` and `touch()` scss mixins with a check for `host-context(html.is-touch)` to fix broken hover behaviour on `chip` + broken focus behaviour on `button`, `dropdown`, `fab-sheet` and `segmented control`
