### ISSUE TITLE
[BUG] kirby checkbox label is not clickable

### ISSUE THREAD

**Issue by HStokbro** [kirbydesign/designsystem#1195]
**Describe the bug**
When inside a label. Then the label should be clickable.

**Kirby version**
    "@kirbydesign/designsystem": "1.2.91",

**Expected behavior**
Make Kirby checkboxes and radio buttons play nice with labels.
Also there should be cookbook examples of checkboxes and radio buttons used with labels

**Screenshots**

**Please complete the following information:**
MacOS, Chrome

**Additional context**
-

## Tasks:
- [x] Move issue from "Ready to do" -> "in progress" on our [project board](https://github.com/kirbydesign/designsystem/projects/1)
- [x] Create Fix Branch
- [x] Create test reproducing the error
- [x] Fix
- [x] If relevant [Update Examples and Showcase](https://cookbook.kirby.design/home/showcase/button)
- [x] Push commits to GitHub
- [ ] Open a pull request (remember to add `closes #issueno` to the description) and ask @kirbydesign/kirby-guild for review
- [ ] Merge to master and delete branch

**Comment by bommariusser** [comment]
@HStokbro have u tried to put the form fields into a selectable item? We know that the cookbook doesn't showcase how to put a label beside the form-field, like checkbox, but this might help. 

@hafstad @jakobe might have some knowledge here :)

**Comment by HStokbro** [comment]
By "selectable item". Do you mean the <kirby-item>?
Yes I tried using <kirby-item>, and then I got the formatting for item with white background etc.

The way I understand the <kirby-item> from the kirby documentation. It is a way to format items in a list. That is a different ui, then what I need. See the screendumps.

Another way I could go is to not use Kirby, and style the checkboxes myself using a regular html checkbox. If this is an edge case.

**Comment by bommariusser** [comment]
@HStokbro yes the kirby-item sorry :) 

Ah yes i see the challenge. So we have it on our radar that the item should be possible to style without any background, see also this task https://github.com/kirbydesign/designsystem/issues/858 - this need came mainly because we realised that we shouldnt overuse the "container/card" in our interfaces.

We have also a task to showcase it better how to use a form with a label, because a label is required when using a form-field like checkbox, radio or toggle. See also task https://github.com/kirbydesign/designsystem/issues/946

Not using Kirby doesn't sound like a good idea :)

Coming back to my question: Does an item solve your main issue? The one where you can click on the label to select the checkbox?

**Comment by HStokbro** [comment]
Okay. I will use the Kirby checkbox.

Using an item does not solve my main issue. You can try clicking the text in the item with a checkbox here: https://cookbook.kirby.design/home/showcase/item

Also, IMO, going down that road may fix a symptom but not fix the issue.
It's just a checkbox with a custom ui. Maybe the component should be simplified instead of adding extra dependencies to other components to get a standard "out of the box" html behavior.

**Comment by HStokbro** [comment]
Ah. Looking through the actual code. Now I know why it does not work.
There is not actually an input type="checkbox" in your kirby-checkbox. (weird)

Instead the checkbox is a button with a checkbox icon and an input type="hidden" to keep the value.

This should be remade into an input type="checkbox" that is styled to be hidden and a :before styling to show the icon. Then you will get the label text click to check the checkbox from standard out of the box html. And you will also not need to handle setting the value in the hidden input. This is the right way to fix the issue.

**Comment by bommariusser** [comment]
in that example in the Cookbok on the item the checkbox isn't activated when pressing on the label - but in our pickers in DRB like "vælg modtager" the items changes its state by clicking on the item. 

The item has defined the styling of a form and a label combined so why bother making custom ui? 

so i'm not the expert which way you should go but you might consider contacting a person that might know more of the actual implementation, like Jakob or Alexander :), because there actually might be a reason why its not in input type, even though it sounds like a good idea :)

**Comment by bommariusser** [comment]
So we talked about it @HStokbro and item is the way to go for a form + label, like in our sketch-library. And @hafstad also mentioned already a possibility to remove the white background, maybe he can help you. And @jakobe mentioned the issue with an item and label as clickable for both checkbox, radio and probably also the toggle that we are aware of, but this should be fixed there.

**Comment by HStokbro** [comment]
This exact issue is fixed in ionic version 5.5.0:
https://github.com/ionic-team/ionic-framework/releases/tag/v5.5.0

Ionic now uses a native <input type="checkbox"

When we upgrade Ionic inside Kirby. The issue should be fixed.

**Comment by HStokbro** [comment]
The ionic checkbox is not built to be used with a normal html label.
It is built to be used inside an ionic-item with an ionic-label, so a standard html label setup is not going to work.

Ionic builds a hidden html label inside the ionic-checkbox and breaks any other html label standard click functionality.
