### ISSUE TITLE
[BUG] Small Button (with icon) should have 12px padding where the icon is placed

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#1207]
**Describe the bug**
Our small buttons have 4px too much padding where the icon is placed. 

**To Reproduce**

1. Go to https://cookbook.kirby.design/home/showcase/button
2. Inspect a small button with an icon
3. See it has 16px padding instead of 12px

**Kirby version**
v1.3.7

**Expected behavior**
Should have 12px padding

**Screenshots**
![Skærmbillede 2020-11-20 kl  08 21 48](https://user-images.githubusercontent.com/49033002/99771953-3a236e80-2b0a-11eb-928b-8406a538c5ff.png)

**Please complete the following information:**
All devices ;) 

**Additional context**
See also zeplin: https://zpl.io/aNXvx4Z

## Tasks:
- [x] Move issue from "Ready to do" -> "in progress" on our [project board](https://github.com/kirbydesign/designsystem/projects/1)
- [x] Create Fix Branch
- [x] Create test reproducing the error
- [x] Fix
- [x] If relevant [Update Examples and Showcase](https://cookbook.kirby.design/home/showcase/button)
- [x] Push commits to GitHub
- [x] Open a pull request (remember to add `closes #issueno` to the description) and ask @kirbydesign/kirby-guild for review
- [ ] Merge to master and delete branch
