### ISSUE TITLE
[BUG] Some "example on github"-links are dead

### ISSUE THREAD

**Issue by MadsBuchmann** [kirbydesign/designsystem#1282]
**Describe the bug**

On the cookbook example pages for the list component, clicking on the "example on github" button sends you to githubs 404 page. 

**To Reproduce**

1. Go to one of the following pages: 

- https://cookbook.kirby.design/home/showcase/list
- https://cookbook.kirby.design/home/showcase/list-load-on-demand
- https://cookbook.kirby.design/home/showcase/list-swipe
- https://cookbook.kirby.design/home/showcase/list-no-shape
- https://cookbook.kirby.design/home/showcase/reorder-list
- https://cookbook.kirby.design/home/showcase/tabs

2. Click on 'example on github'
3. You should see githubs 404 page. 

**Kirby version**
- 1.4.1

**Expected behavior**
Clicking the button  should take me to the code on github, as it does on the action-sheet component page (https://cookbook.kirby.design/home/showcase/action-sheet).

**Please complete the following information:**
- OS: MacOS
- Browser: Firefox
- Browser version: 85.0

## Tasks:
- [x] Move issue from "Ready to do" -> "in progress" on our [project board](https://github.com/kirbydesign/designsystem/projects/1)
- [x] Create Fix Branch
- [ ] Create test reproducing the error
- [x] Fix
- [x] If relevant [Update Examples and Showcase](https://cookbook.kirby.design/home/showcase/button)
- [x] Push commits to GitHub
- [x] Open a pull request (remember to add `closes #issueno` to the description) and ask @kirbydesign/kirby-guild for review
- [ ] Merge to master and delete branch
