### ISSUE TITLE
[BUG] Modal outlet in portals

### ISSUE THREAD

**Issue by hafstad** [kirbydesign/designsystem#1285]
**Describe the bug**
Modal outlets used with portals in DRB doesn't work properly as it's doesn't recognise the route as a modal route, which means that the modal won't open

**Expected behavior**
Modal with outlet would open as used to even though it's inside of a portal

## Tasks:
- [x] Move issue from "Ready to do" -> "in progress" on our [project board](https://github.com/kirbydesign/designsystem/projects/1)
- [ ] Create Fix Branch
- [ ] Create test reproducing the error
- [ ] Fix
- [ ] If relevant [Update Examples and Showcase](https://cookbook.kirby.design/home/showcase/button)
- [ ] Push commits to GitHub
- [ ] Open a pull request (remember to add `closes #issueno` to the description) and ask @kirbydesign/kirby-guild for review
- [ ] Merge to master and delete branch
