### ISSUE TITLE
[Enhancement] tslint -> eslint

### ISSUE THREAD

**Issue by hafstad** [kirbydesign/designsystem#1317]
**Is your enhancement request related to a problem? Please describe.**
tslint is deprecated, and we should therefore move to eslint 

**Describe the solution you'd like**
Migrate to eslint

### Things to consider
- https://blog.nrwl.io/automatically-migrating-angular-applications-from-tslint-to-eslint-using-nx-58d22a895206
- Wait for #1318 (because Angular 11)
- Use `prettier` as a plugin for ESLint

### Resources

- [Migrating and configuring Eslint with Angular 11](https://dev.to/gsarciotto/migrating-and-configuring-eslint-with-angular-11-3fg1)
- https://github.com/angular-eslint/angular-eslint

### Tasks

- [ ] Do the migration
- [ ] Configure ESLint if something is missing, e.g. _ordered imports_, _codelyzer_ and rules that can't be matched by the migration tools (if no ESLint equivalent rule)
- [ ] Fix any unforeseen issues
- [ ] Verify that linting and formatting works as intended
- [ ] Inform devs if they need to do anything, e.g., uninstall or disable extensions from their code editor/IDE and such.

**Comment by jakobe** [comment]
![giphub](https://media4.giphy.com/media/wi8Ez1mwRcKGI/giphy.gif)

**Comment by alxzak** [comment]
Waiting for angular 11 #1318
