### ISSUE TITLE
[BUG] Add SizeDirective to our mocks (kirby-testing-base.module.ts)

### ISSUE THREAD

**Issue by hafstad** [kirbydesign/designsystem#1335]
**Describe the bug**
As a consumer of kirby who has used the `SizeDirective ` ex. setting the size of an `kirby-icon` you will get following error, because we haven't included a mock for it:
`Can't bind to 'size' since it isn't a known property of 'kirby-icon'.` 

**Kirby version**
- 1.4.6

**Expected behavior**
You should receive no errors because you have imported `KirbyTestingModule` which should handle the mocking for you. 

**Additional information**
Our mocks are located here:
`libs/designsystem/testing-base/src/lib`

## Tasks:
- [x] Move issue from "Ready to do" -> "in progress" on our [project board](https://github.com/kirbydesign/designsystem/projects/1)
- [ ] Create Fix Branch
- [ ] Create test reproducing the error
- [ ] Fix
- [ ] If relevant [Update Examples and Showcase](https://cookbook.kirby.design/home/showcase/button)
- [ ] Push commits to GitHub
- [ ] Open a pull request (remember to add `closes #issueno` to the description) and ask @kirbydesign/kirby-guild for review
- [ ] Merge to master and delete branch
