### ISSUE TITLE
[BUG] Can't change list color after it is set

### ISSUE THREAD

**Issue by lydemann** [kirbydesign/designsystem#1336]
**Describe the bug**

Can't change list color after it is set as the css color directive in list component is only appending color classes but is not able to change them later.

**To Reproduce**

1. Add color to list item using color CB
2. Try to change color
3. See still same color as in step 1

**Kirby version**
- [e.g. 1.1.10]

**Expected behavior**

**Please complete the following information:**
- OS: [e.g. Windows, MacOS, iOS]
- Browser [e.g. Chrome, Safari]
- Browser version [e.g. 22]

**Additional context**

## Tasks:
- [x] Move issue from "Ready to do" -> "in progress" on our [project board](https://github.com/kirbydesign/designsystem/projects/1)
- [x] Create Fix Branch
- [ ] Create test reproducing the error
- [ ] Fix
- [ ] If relevant [Update Examples and Showcase](https://cookbook.kirby.design/home/showcase/button)
- [ ] Push commits to GitHub
- [ ] Open a pull request (remember to add `closes #issueno` to the description) and ask @kirbydesign/kirby-guild for review
- [ ] Merge to master and delete branch
