### ISSUE TITLE
[BUG] Button is still in focus after the user releases the button (tint color stays on)

### ISSUE THREAD

**Issue by LVinther** [kirbydesign/designsystem#1340]
**Describe the bug**

This is a mobile-only issue! Right now when a user presses a button the button stays the tint color even after the user has stopped pressing the button. 

**To Reproduce**

1. Go to the cookbook on your phone
2. Select the Button component
3. Press on a button and release
4. See that the button is still the tint color

**Kirby version**
1.3.25

**Expected behavior**
When the user clicks presses the button the button should have the tint color. When the user releases the button it should not have the tint color but the base color.  

**Screenshots**

Before pressed:
![IMG_21B92310E54F-1](https://user-images.githubusercontent.com/53176253/108481833-f3741a80-7298-11eb-9f95-33425c5955c4.jpeg)

After pressed:
![IMG_21B92310E54F-2](https://user-images.githubusercontent.com/53176253/108481830-f242ed80-7298-11eb-9f69-66f44c8e82a8.jpeg)

**Please complete the following information:**
- iOS iPhone 8
- Browser: Safari

**Additional context**
We need this behavior to be corrected for our star marking on the paper detail page. Right now the star marking remains tint color (grey instead og black) after pressed state.  

## Tasks:
- [x] Move issue from "Ready to do" -> "in progress" on our [project board](https://github.com/kirbydesign/designsystem/projects/1)
- [x] Create Fix Branch
- [ ] Create test reproducing the error
- [x] Fix
- [ ] If relevant [Update Examples and Showcase](https://cookbook.kirby.design/home/showcase/button)
- [x] Push commits to GitHub
- [x] Open a pull request (remember to add `closes #issueno` to the description) and ask @kirbydesign/kirby-guild for review
- [ ] Merge to master and delete branch

**Comment by LVinther** [comment]
@henrikvoetmand så er bug'en på buttons oprettet. Det er et mobile-only problem :) Er der andet jeg skal gøre?

**Comment by bommariusser** [comment]
det er ikke på appen vel @LVinther ? :) jeg tror det er i cookbooken fordi den beholder focus state når man har trykket.

**Comment by LVinther** [comment]
@bommariusser det er også på App'en :) Det viste sig nemlig på den stjernemarkering vi er ved at bygge på Favoritter :)

**Comment by bommariusser** [comment]
ok men den ligger i toolbaren eller? :) @LVinther du henviser til en rød knap nemlig :D

**Comment by jakobe** [comment]
Tech refinement: Button should not have opacity 0.8 on :focus state

**Comment by LVinther** [comment]
@bommariusser Ja stjernen ligger i toolbaren, men da den ikke er bygget endnu, så henviste jeg bare til opførslen på knapper i cookbook, da det er det eneste sted jeg kunne vise det :) I app'en navigere vores knapper nemlig altid videre eller åbner noget, så der kan man ikke se det :)

**Comment by RasmusKjeldgaard** [comment]
In addition to fixing this specific bug, the change also makes sure that the button element will only have an outline but no tint when in focus (e.g. via tabindex).
