### ISSUE TITLE
[HOUSEKEEPING] Modal tests randomly fail

### ISSUE THREAD

**Issue by MadsBuchmann** [kirbydesign/designsystem#1353]
**Describe the bug**
The two tests on the screenshot randomly fail/succeed: 
<img width="790" alt="Screenshot 2021-02-24 at 13 28 05" src="https://user-images.githubusercontent.com/17269698/109000655-489e9a80-76a4-11eb-9818-ecbdd20e9ff9.png">

**To Reproduce**

1. Execute `npm run test:headless-browser`
2. Repeat step 1 until the tests fail

**Kirby version**
- v1.4.14

**Expected behavior**
It should be consistent whether the tests fail or succeed. The randomness of the outcome essentially makes the tests useless, as it is not certain whether a change caused the tests to fail or it is just random. 

**Please complete the following information:**
- OS: MacOs 11.2.1
- Node: 10.16.3

## Tasks:
- [x] Move issue from "Ready to do" -> "in progress" on our [project board](https://github.com/kirbydesign/designsystem/projects/1)
- [x] Create Fix Branch
- [ ] Create test reproducing the error
- [ ] Fix
- [ ] If relevant [Update Examples and Showcase](https://cookbook.kirby.design/home/showcase/button)
- [ ] Push commits to GitHub
- [ ] Open a pull request (remember to add `closes #issueno` to the description) and ask @kirbydesign/kirby-guild for review
- [ ] Merge to master and delete branch

**Comment by jakobe** [comment]
The reason for this functionality is to avoid a jagged leave/close animation of the modal if the viewport is resizing due to a native keyboard being hidden while at the same time running the modal leave animation.
Maybe this can be fixed by using Ionic's keyboard lifecycle events? https://ionicframework.com/docs/developing/keyboard#keyboard-lifecycle-events

**Comment by jakobe** [comment]
Closed by #1445
