### ISSUE TITLE
[BUG] loading indicator and "no more items"-text is misaligned in list

### ISSUE THREAD

**Issue by MadsBuchmann** [kirbydesign/designsystem#1371]
**Describe the bug**

The loading indicator and "no more items"-text on the list component is not properly aligned. 

**To Reproduce**

1. Go to https://cookbook.kirby.design/examples/list-load-on-demand
2. Scroll to the bottom of the page
3. The misaligned loading indicator should now appear
4. Keep scrolling to see the misaligned "no more items"-text. 

**Kirby version**
- v. 1.4.17. 

**Expected behavior**
It should be centered directly below the list. 

**Please complete the following information:**
- OS: MacOS
- Browser Safari 
- Browser version 14.0.3

**Additional context**

## Tasks:
- [X] Have the bug report verified by contacting a member of @kirbydesign/kirby-guild
- [ ] Move issue from "Ready to do" -> "in progress" on our [project board](https://github.com/kirbydesign/designsystem/projects/1)
- [ ] Create Fix Branch
- [ ] Create test reproducing the error
- [ ] Fix
- [ ] If relevant [Update Examples and Showcase](https://cookbook.kirby.design/home/showcase/button)
- [ ] Push commits to GitHub
- [ ] Open a pull request (remember to add `closes #issueno` to the description) and ask @kirbydesign/kirby-guild for review
- [ ] Merge to master and delete branch
