### ISSUE TITLE
[BUG] Modal outlet (through a portal) - Angular router bug

### ISSUE THREAD

**Issue by hafstad** [kirbydesign/designsystem#1381]
**Describe the bug**
Using modal outlets in DRB in combination of portals Angular's own router kicks in, and results in unexpected behaviours / errors

**To Reproduce**

1. Go to http://localhost:4200/drb/micro/cards
2. Click on 'Bestil kort'
3. Choose a card (which opens a modal with outlet) - e-tax.component.ts
4. Choose '75.000' and click 'fortsæt'
5. Click on 'send' (which opens a modal with a component)
6. You will now see the expected component passed to the modal but if you scroll down, you will also see the modal outlet component (because Angular router, has inserted it) - e-tax.component.ts

**Kirby version**
- 1.4.19

**Expected behavior**
on step 6, modal outlet component should not be shown

**Additional context**
Following could fix the issue: 

1. Instead of having visibility at router-outlet (inside modal-wrapper), which actually does nothing because the component is created separately and not inside it, add *ngIf instaed
2. Rename router-outlet (inside modal-wrapper) to something like "kirbyModalWrapperOutlet" which doesn't conflict with the outlet name consumers of Kirby uses.  

## Tasks:
- [x] Have the bug report verified by contacting a member of @kirbydesign/kirby-guild
- [x] Move issue from "Ready to do" -> "in progress" on our [project board](https://github.com/kirbydesign/designsystem/projects/1)
- [ ] Create Fix Branch
- [ ] Create test reproducing the error
- [ ] Fix
- [ ] If relevant [Update Examples and Showcase](https://cookbook.kirby.design/home/showcase/button)
- [ ] Push commits to GitHub
- [ ] Open a pull request (remember to add `closes #issueno` to the description) and ask @kirbydesign/kirby-guild for review
- [ ] Merge to master and delete branch

**Comment by jakobe** [comment]
I can recreate the bug in the DRB project when loading the affected module through the "portal" wiring - but when loading the module through Angular's lazy loaded route (deep linking to the affected module) the bug isn't there.
In other words: This is not a Kirby bug as such, but a bug coming from the way the DRB project manually compiles/loads a module in the given scenario.
