### ISSUE TITLE
[BUG] Setting minDate and maxDate in CalendarComponent causes null ref (activeMonth not defined)

### ISSUE THREAD

**Issue by lydemann** [kirbydesign/designsystem#1385]
**Describe the bug**
[BUG] Setting minDate and maxDate in CalendarComponent causes null ref (activeMonth not defined)

**To Reproduce**

1. Set maxDate in CalendarComponent
2. See null ref error ala:
<img width="1792" alt="Screen Shot 2021-03-04 at 12 31 58" src="https://user-images.githubusercontent.com/9210691/109958392-760fc780-7ce6-11eb-8157-ade5d5f0303c.png">

**Expected behavior**
Should not throw error. Based on this implementation:
```
  <kirby-calendar
      [disableWeekends]="true"
      [maxDate]="maxDate"
      [selectedDate]="selectedDate"
      [todayDate]="todayDate"
      (dateChange)="onDateSelected($event)"
    >
    </kirby-calendar>
```

**Screenshots**
<img width="1792" alt="Screen Shot 2021-03-04 at 12 31 58" src="https://user-images.githubusercontent.com/9210691/109958443-845de380-7ce6-11eb-905f-0990e0894b45.png">

![image](https://user-images.githubusercontent.com/30232520/109974636-0dcae100-7cfa-11eb-88c2-5fe3f7fee187.png)

**Please complete the following information:**
- OS: [e.g. Windows, MacOS, iOS]
- Browser [e.g. Chrome, Safari]
- Browser version [e.g. 22]

High priority, blocking functionality in Drb.

## Tasks:
- [x] Have the bug report verified by contacting a member of @kirbydesign/kirby-guild
- [x] Move issue from "Ready to do" -> "in progress" on our [project board](https://github.com/kirbydesign/designsystem/projects/1)
- [x] Create Fix Branch
- [x] Create test reproducing the error
- [x] Fix
- [x] If relevant [Update Examples and Showcase](https://cookbook.kirby.design/home/showcase/button)
- [x] Push commits to GitHub
- [x] Open a pull request (remember to add `closes #issueno` to the description) and ask @kirbydesign/kirby-guild for review
- [ ] Merge to master and delete branch
