### ISSUE TITLE
[BUG] Wrong text colour (white) in actionsheet items and icon colour (white) in "more" icon.  

### ISSUE THREAD

**Issue by henrikvoetmand** [kirbydesign/designsystem#1395]
**Describe the bug**
In "Skjern Bank" version of DRB some Action sheet items have white text on white background. Some icons eg. "more" menu action and "close" action is white on light grey background.

**To Reproduce**

1. Install Skjern Bank DRBMock
2. Go to 'Indbakke'
2. Click on 'Dokumenter'
3. In top right corner you see white icon (more menu)
4. Click on "more" icon
5. Action sheet item has white text on white background.

**Kirby version**
- [e.g. 1.4.21]

**Expected behavior**
Text and icons should be dark grey "#black-base"

**Screenshots**
![IMG_2403](https://user-images.githubusercontent.com/71710012/110486408-ea82a600-80ec-11eb-9eb0-39c346554893.png)
![IMG_2404](https://user-images.githubusercontent.com/71710012/110486414-eb1b3c80-80ec-11eb-8485-2507f204bf6e.png)

**Please complete the following information:**
- OS: [ iOS]

**Additional context**
Comps der bruger primary-contrast uden at forholde sig til den reelle bg farve:
![image (6)](https://user-images.githubusercontent.com/71710012/110486883-5d8c1c80-80ed-11eb-8a9f-1d523f4f0426.png)

PI's will start to test the app by end march. Please have this bug fixed by mid april at the latest. 

## Tasks:
- [x] Have the bug report verified by contacting a member of @kirbydesign/kirby-guild
- [x] Move issue from "Ready to do" -> "in progress" on our [project board](https://github.com/kirbydesign/designsystem/projects/1)
- [x] Create Fix Branch
- [ ] Create test reproducing the error
- [ ] Fix
- [ ] If relevant [Update Examples and Showcase](https://cookbook.kirby.design/home/showcase/button)
- [ ] Push commits to GitHub
- [ ] Open a pull request (remember to add `closes #issueno` to the description) and ask @kirbydesign/kirby-guild for review
- [ ] Merge to master and delete branch

**Comment by jkaltoft** [comment]
After (Kirby v1.4.44)

"More" icon | Action sheet
---- | ----
![IMG_0896](https://user-images.githubusercontent.com/150451/115357772-46951b80-a1bd-11eb-829a-cbc99b462c87.PNG) | ![IMG_0897](https://user-images.githubusercontent.com/150451/115357842-557bce00-a1bd-11eb-95b6-b8aaee985124.PNG)
