### ISSUE TITLE
[BLOCKED][BUG] Dropdown doesn't popout correctly when the height of the popped out card reaches the viewport of its container

### ISSUE THREAD

**Issue by MartinSkovsen** [kirbydesign/designsystem#1411]
**Describe the bug**

When Calendar with year navigator is used inside a modal with drawer flavor, its dropdown doesn't actually popout to the left as it is supposed to - under some circumstances. When there are more years in the year navigator (which is a kirby-dropdown), than the drawer can contain in the height (the dropdown reaches viewport), it pops up instead of popping out left.

So **the general issue** is that when the dropdown container is not heigh enough to contain the popout card, dropdown pops the card out to the top, and, depending on the css of the container, it'll cut the popped out card off with for example overflow:hidden.

Specifically, the reason, why the dropdown pops upwards, is [this section of code in the dropdown component](https://github.com/kirbydesign/designsystem/blob/master/libs/designsystem/src/lib/components/dropdown/dropdown.component.ts#L277-L293).

**To Reproduce**

1. Get the cookbook locally
2. Modify the first embedded example for modals by deleting all the content in kirby-loading-overlay and insert a year navigator configured calendar with 50 years
3. ng serve the project and go to /showcase/modal
4. Open up the drawer
5. Pop out the year navigator
6. It should pop up instead popping out left - depending on the (height of the) container. If you are on desktop and open dev tools and put it in the bottom of the screen, you might get the correct, expected pop out.

**Kirby version**
- 1.4.21

**Expected behavior**

The dropdown should popout to the left - and not collide with the viewport.

**Screenshots**

**Please complete the following information:**
- OS: Windows, Mac
- Browser: Chrome, Brave, Firefox
- Browser version: Newest

**Additional context**
This bug is occuring in a branch, which is about to be merged to the relationsbank. it is supposed to be released on 1/5, so it does have some value to prioritize this issue.

[Link to Team 9s implementation](https://github.com/Bankdata/relationsbank/pull/4182/files#diff-62d43da259f040b49c0628dc081f5be0ea941e462b64d400014abcb739e16690R10-R48)

Screenshot: ![billede](https://user-images.githubusercontent.com/30232520/111428891-72257180-86f8-11eb-9738-4657c4960caa.png)

## [Blocked] 
Currently blocked by: #1671
The popover functionality that is introduced in this PR should be used to solve this issue. 

## Tasks:
- [x] Have the bug report verified by contacting a member of @kirbydesign/kirby-guild
- [x] Move issue from "Ready to do" -> "in progress" on our [project board](https://github.com/kirbydesign/designsystem/projects/1)
- [x] Create Fix Branch
- [ ] Create test reproducing the error
- [ ] Fix
- [ ] If relevant [Update Examples and Showcase](https://cookbook.kirby.design/home/showcase/button)
- [ ] Push commits to GitHub
- [ ] Open a pull request (remember to add `closes #issueno` to the description) and ask @kirbydesign/kirby-guild for review
- [ ] Merge to master and delete branch

**Comment by MartinSkovsen** [comment]
I have been unable to reproduce this issue in the cookbook. When reproduced in the cookbok it behaves as expected. I'm looking into this on the particular branch together with @RasmusTraeholt

**Comment by MartinSkovsen** [comment]
Using the relationsbank branch I can reproduce the bug about half of times I pop the dropdown out. The half it works just fine. Even with a lot of years (so a looong dropdown).

**Comment by MartinSkovsen** [comment]
After some more manual testing and discussions with @jakobe, it semms this is a problem with the viewport size and the height of dropdown.

**Comment by MartinSkovsen** [comment]
For a clear description of the bug, see [the bug discription on the issue](https://github.com/kirbydesign/designsystem/issues/1411)

**Comment by MartinSkovsen** [comment]
This issue originally became relevant because the dropdown is not confined in the calendar. If the dropdown does get confined in the calendar as a part of the solution to #1399, this bug might not be relevant anymore. @RasmusKjeldgaard As you are now assigned to #1399, I'll also assign you to this one, so we can get the necessary clarification on how to proceed with the bug.

**Comment by MortenGregersen** [comment]
I have a problem using the dropdown in a card. When there is no content for the chosen filter (an item in the dropdown), the card is empty. It makes the card just slightly larger than the dropdown, but when I click the dropdown, I can't see the items because they are hidden "outside" the card.
![Screenshot 2021-04-27 at 09 37 42](https://user-images.githubusercontent.com/759680/116211419-119c4200-a744-11eb-81a5-6c6e85201b99.png)

**Comment by bommariusser** [comment]
@MortenGregersen can you show the whole screen morten? :)

**Comment by MortenGregersen** [comment]
@bommariusser Der sker ikke rigtig andet på skærmen der har relevans. Det er et Kirby card med en grøn card header og en dropdown. Card'et har `hasPadding="true"` og på billedet er dropdown'en "foldet ud".

**Comment by jkaltoft** [comment]
Suspended/blocked until PoC of generic pop-out/pop-over has been done in connection with solving #404

**Comment by MadsBuchmann** [comment]
Closed related PR with #1540 (see reason in closing comment). 
But it might still be useful for inspiration.

**Comment by MadsBuchmann** [comment]
A fix for this - which requires some more testing with the `usePopover` functioanlity is to make the following change

```html
--- a/libs/designsystem/src/lib/components/calendar/calendar.component.html
+++ b/libs/designsystem/src/lib/components/calendar/calendar.component.html
@@ -14,6 +14,7 @@
     </button>
   </div>
   <kirby-dropdown
+    [usePopover]="true"
     *ngIf="_hasYearNavigator"
     [selectedIndex]="navigatedYear"
     [items]="navigableYears"
```

**Comment by RasmusTraeholt** [comment]
`usePopover` does not work in iOS or Android native browsers (it is not possible to scroll in the dropdown list). It works fine in standard desktop browsers though.

**Comment by RasmusKjeldgaard** [comment]
> `usePopover` does not work in iOS or Android native browsers (it is not possible to scroll in the dropdown list). It works fine in standard desktop browsers though.

That should be fixed in https://github.com/kirbydesign/designsystem/issues/2204, which will most likely be released with Kirby v6.

**Comment by RasmusTraeholt** [comment]
> > `usePopover` does not work in iOS or Android native browsers (it is not possible to scroll in the dropdown list). It works fine in standard desktop browsers though.
> 
> That specific problem should be fixed in #2204, which will most likely be released with Kirby v6.

I noticed it is not possible to select an item in a standard dropdown component with `usePopover` either. Will that be fixed with above mentioned release as well?

**Comment by RasmusKjeldgaard** [comment]
> > > `usePopover` does not work in iOS or Android native browsers (it is not possible to scroll in the dropdown list). It works fine in standard desktop browsers though.
> > 
> > 
> > That specific problem should be fixed in #2204, which will most likely be released with Kirby v6.
> 
> I also noticed it is not possible to select an item in a standard dropdown component with `usePopover` either (on iOS and Android). Will that be fixed with above mentioned release as well?

Yes, that should be fixed too.
