### ISSUE TITLE
[EPIC] Replace HighCharts with Chart.js 

### ISSUE THREAD

**Issue by hafstad** [kirbydesign/designsystem#1413]
**Please add a short description of your enhancement request**
Replace HighCharts with Chart.js

**Describe the solution you'd like**
Kirby charts using Chart.js instead of HighCharts

**Additional context**

- It's has been decided that this is going to be a breaking change due to the huge differences between HighCharts and Chart.js api's 
- Currently it's only collumn and bar chart which are used in DRB, other chart types can be implemented later on
- Highcharts should be removed from our dependencies libs/designsystem/package.json & ng-package.json
- Chart.js should be added to our dependencies libs/designsystem/package.json & ng-package.json

### Kick Off:

- [x] Ensure the enhancement is `UX refined` and aligned with UX 
_The component and/or enhancement should be published and available in the [Kirby Styleguide on Zeplin](https://zpl.io/258pXGj)_
- [x] Ensure the enhancement has been `Tech refined` with @kirbydesign/kirby-guild and this issue is updated with a clear implementation description  
_This issue should be in the [Ready to do](https://github.com/kirbydesign/designsystem/projects/1#column-4590936) column of the [Kirby kan-ban board](https://github.com/kirbydesign/designsystem/projects/1) before starting implementation)_
- [x] Assign yourself to this issue and move it to the [In progress](https://github.com/kirbydesign/designsystem/projects/1#column-4590937) column of the [Kirby kan-ban board](https://github.com/kirbydesign/designsystem/projects/1)

### Code:

- [x] Create Feature Branch from [master branch](https://github.com/kirbydesign/designsystem/tree/master)
- [x] Create a draft implementation and push to Github
- [x] Ask a member of @kirbydesign/kirby-guild for a WIP review by creating a draft Pull Request
- [ ] Implement unit tests
- [x] Update Cookbook Examples and Showcase, i.e. see [Radio](https://cookbook.kirby.design/home/showcase/radio)  
_Also remember to add any relevant new API documentation_

### Review:

- UX review:
  - [ ] Ensure implementation is correct in relation to the UX design and the [Kirby Styleguide on Zeplin](https://zpl.io/258pXGj)
  - [ ] With UX agree on the version of the implementation
- Code review:
  - [ ] Open a pull request (or mark the existing draft PR as `Ready for review`) and ask @kirbydesign/kirby-guild for a review  
_Remember to add `closes #issueno` to the description of the PR._
  - [ ] Once approved, merge feature branch/PR to master
- [ ] Ask a member of @kirbydesign/kirby-guild to add a link to component showcase from Kirby Component Status and update the version number

:tada: Celebrate

**Comment by RasmusKjeldgaard** [comment]
Discussion of ChartJS component, based on previous work in Team 3 and Team Apollo:

### Sensible defaults
- Make the Kirby chart simple to use out-of-the-box, with minimal setup
  - A chart type, and a simple array `data: [3, 5, 8]` should produce basic charts.
- Expose the ChartJS API so sensible defaults can be overwritten if there are custom requirements
  - How much control over options on `datasets` should the users of the component have?
- Consider if we enable certain general plugins by default, like [annotations](https://www.chartjs.org/chartjs-plugin-annotation/guide/usage.html), so it is opt-out.

### Other stuff
- Separate configuration, so it is global where appropriate, and otherwise overwritten in each chart instance 
  - https://www.chartjs.org/docs/latest/configuration/
- It should be trivial to supply data to the chart, and arithmetics to show the output correctly should be done inside the component.
  - We want to avoid complex cookbook examples [like this](https://github.com/kirbydesign/designsystem/pull/1509/files#diff-b03f35feea0b068c3e1de2acc4cabbc09958612ab25ab064129f2721ed2c3aeeR50)
- While developing the new ChartJS component, it will live besides the existing `kirby-chart` component, so they can be easily compared.
  - Before merging the solution, we will rename the ChartJS component to `kirby-chart` and remove the highcharts implementation. This will be a breaking change once released.

**Comment by MadsBuchmann** [comment]
Related issue: https://github.com/kirbydesign/designsystem/issues/1073

**Comment by MadsBuchmann** [comment]
I've broken this up into several small issues - see the above references ⬆️

**Comment by MadsBuchmann** [comment]
Upon talking with @henrikvoetmand & @jakobe the charts should be visually recreated like the old ones.

**Comment by MadsBuchmann** [comment]
still relevant
