### ISSUE TITLE
[BUG] Modal route with query params not working after back navigation

### ISSUE THREAD

**Issue by jakobe** [kirbydesign/designsystem#1452]
**Describe the bug**
A Modal route with query params stops working after back navigation

**To Reproduce**

1. Go to https://cookbook.kirby.design/home/showcase/modal
2. Click on "Open modal by route" or "Open modal by router link" under the "With modal outlet:" heading
3. Click the browsers back button
4. The modal doesn't close when navigating back
Same error happens when clicking the "Deep link to modal route" or "Deep link to modal by router link", navigate back and clicking the link again => the modal doesn't open after 1st navigation.

**Kirby version**
- [e.g. 1.1.10]

**Expected behavior**
Modal closes on back navigation / modal can be re-opened after navigating back from deeplink and clicking deeplink again.

**Screenshots**

**Please complete the following information:**
- OS: Windows, MacOS
- Browser: Chrome, Safari, etc.
- Browser version: all

## Tasks:
- [X] Have the bug report verified by contacting a member of @kirbydesign/kirby-guild
- [X] Move issue from "Ready to do" -> "in progress" on our [project board](https://github.com/kirbydesign/designsystem/projects/1)
- [x] Create Fix Branch
- [ ] Create test reproducing the error
- [x] Fix
- [ ] If relevant [Update Examples and Showcase](https://cookbook.kirby.design/home/showcase/button)
- [x] Push commits to GitHub
- [x] Open a pull request (remember to add `closes #issueno` to the description) and ask @kirbydesign/kirby-guild for review
- [ ] Merge to master and delete branch
