### ISSUE TITLE
[Enhancement] Remove toolbar component

### ISSUE THREAD

**Issue by alxzak** [kirbydesign/designsystem#1459]
## Tasks
Remove toolbar from Kirby
### Code:

- [ ] Remove Toolbar from github
- [ ] Remove Toolbar from Cookbook
- [ ] Remove toolbar from sketch
- [ ] Smile

### Review:

- UX review:
  - [ ] With UX agree on the absence of the implementation
- Code review:
- [ ] Ask a member of @kirbydesign/kirby-guild to remove the link from component showcase from Kirby Component Status and update the version number

:tada: Celebrate
