### ISSUE TITLE
[BUG] Global modal size classes

### ISSUE THREAD

**Issue by tja1607** [kirbydesign/designsystem#1471]
**Describe the bug**
modal size class is not prefixed. This conflicts with styling when is used on jyskebank.dk , because this classes are globale defined

**To Reproduce**

1. Go to https://wcm2-jyskebank-dk-t.bdunet.dk/bolig/boliglaan/kurser
2. Click on a table item (tr)
3. See error

**Kirby version**
1.4.41

**Expected behavior**
Global classes by Kirby should be prefixed to avoid conflicts.
  
**Screenshots**
![image](https://user-images.githubusercontent.com/3206272/115007517-599ca880-9eaa-11eb-8c3c-ed982055a8ac.png)

**Please complete the following information:**
- OS: [e.g. Windows, MacOS, iOS]
- Browser [e.g. Chrome, Safari]
- Browser version [e.g. 22]

**Additional context**

## Tasks:
- [x] Have the bug report verified by contacting a member of @kirbydesign/kirby-guild
- [x] Move issue from "Ready to do" -> "in progress" on our [project board](https://github.com/kirbydesign/designsystem/projects/1)
- [x] Create Fix Branch
- [x] Create test reproducing the error
- [x] Fix
- [x] If relevant [Update Examples and Showcase](https://cookbook.kirby.design/home/showcase/button)
- [x] Push commits to GitHub
- [x] Open a pull request (remember to add `closes #issueno` to the description) and ask @kirbydesign/kirby-guild for review
- [ ] Merge to master and delete branch
