### ISSUE TITLE
Kirby-radio-group throws an error

### ISSUE THREAD

**Issue by bdudfr** [kirbydesign/designsystem#1476]
**Describe the bug**

When using a `kirby-radio-group`, an error is thrown/logged in the console and an error toast appears.
The error occurs when selecting/clicking a `kirby-radio` item and then clicking somewhere random on the page.
See screenshot of error:
![Screenshot 2021-04-19 at 13 42 22](https://user-images.githubusercontent.com/51995428/115237003-53adfe00-a11c-11eb-8009-77c4bae6b087.png)

The error started occurring after creating a new branch from master. I did a reinstall of node_modules but it did not fix the error.

**To Reproduce**

Using the simplest example from cookbook on a random DRB page results in the error:
<kirby-radio-group [items]="['Bacon', 'Salami', 'Tenderloin']"></kirby-radio-group> 

**Kirby version**
- [1.4.32]

**Expected behavior**

**Screenshots**
![Screenshot 2021-04-19 at 13 42 22](https://user-images.githubusercontent.com/51995428/115237536-f6ff1300-a11c-11eb-9e8f-cc74da86558e.png)

**Please complete the following information:**
- OS: MacOS
- Browser Chrome

**Additional context**

## Tasks:
- [x] Have the bug report verified by contacting a member of @kirbydesign/kirby-guild
- [x] Move issue from "Ready to do" -> "in progress" on our [project board](https://github.com/kirbydesign/designsystem/projects/1)
- [x] Create Fix Branch
- [ ] Create test reproducing the error
- [x] Fix
- [ ] If relevant [Update Examples and Showcase](https://cookbook.kirby.design/home/showcase/button)
- [x] Push commits to GitHub
- [x] Open a pull request (remember to add `closes #issueno` to the description) and ask @kirbydesign/kirby-guild for review
- [ ] Merge to master and delete branch
