### ISSUE TITLE
[Housekeeping] Modal example TODO comment

### ISSUE THREAD

**Issue by MadsBuchmann** [kirbydesign/designsystem#1484]
**Short description of housekeeping request**

When working in the file `apps/cookbook/src/app/examples/examples.common.ts` I encountered a TODO comment on line 92: 
```
 92   // TODO: Move Modal examples to ModalExample.module
 93   ModalExampleComponent,
 94   ModalExampleDefaultComponent,
 95   ModalExampleConfigurationComponent,                                                              
 96   ModalExampleOutletComponent,                                                  
 97   FirstEmbeddedModalExampleComponent,                                                        
 98   SecondEmbeddedModalExampleComponent,                                                            
 99   ModalCompactExampleComponent,                                                          
100   ModalRoutePage1ExampleComponent,                                                              
101   ModalRoutePage2ExampleComponent,                                              
102   // END TODO: Move Modal examples to ModalExample.module           
```

I have not written it. But I suppose the modal examples should be moved to `ModalExample.module` as specified. 

## Alternative 
Remove the comment and don't move the examples to `ModalExample.module`. 

### Kick Off

* [ ] Ensure this issue has been `Tech refined` with @kirbydesign/kirby-guild and is updated with a clear implementation description
  _This issue should be in the [Ready to do](https://github.com/kirbydesign/designsystem/projects/1#column-4590936) column of the [Kirby kan-ban board](https://github.com/kirbydesign/designsystem/projects/1) before starting implementation_
* [ ] Assign yourself to this issue and move it to the [In progress](https://github.com/kirbydesign/designsystem/projects/1#column-4590937) column of the [Kirby kan-ban board](https://github.com/kirbydesign/designsystem/projects/1)

### Code

* [ ] Create Feature Branch from [master branch](https://github.com/kirbydesign/designsystem/tree/master)
* [ ] Implement/update unit tests
* [ ] Create a draft implementation and push to Github
* [ ] Ask a member of @kirbydesign/kirby-guild for a WIP review by creating a draft Pull Request

### Code Review

* [ ] Open a pull request (or mark the existing draft PR as `Ready for review`) and ask @kirbydesign/kirby-guild for a review
  _Remember to add `closes #issueno` to the description of the PR._
* [ ] Once approved, merge feature branch/PR to master

:tada: Celebrate
