### ISSUE TITLE
[BUG] Wrong active link in cookbook

### ISSUE THREAD

**Issue by MadsBuchmann** [kirbydesign/designsystem#1489]
**Describe the bug**

When clicking a `routerLink` on a Cookbook showcase page (that is not part of the menu), the wrong menu item is highlighted. 

**To Reproduce**
I discovered this when working on an unpublished branch. But:

1.  Insert this on a showcase page: `<a [routerLink]="/home/showcase/page">the page showcase</a>`
2. Click the link you inserted in step 1
3. Observe that the wrong menu item is highlighted

**Kirby version**
- 1.5.2

**Expected behavior**

I would expect for the menu item of the page I am currently on to be highlighted. 

For example In the following gif, after having clicked the link I would expect the _page_ menu item to be highlighted instead, not _toolbar_ . 
![Apr-21-2021 14-35-21](https://user-images.githubusercontent.com/17269698/115554659-ff875300-a2ae-11eb-8d1f-a73e8e6c51ce.gif)

**Screenshots**

**Please complete the following information:**
- OS: MacOS
- Browser Safari
- Browser version 14.0.3

## Tasks:
- [X] Have the bug report verified by contacting a member of @kirbydesign/kirby-guild
- [ ] Move issue from "Ready to do" -> "in progress" on our [project board](https://github.com/kirbydesign/designsystem/projects/1)
- [ ] Create Fix Branch
- [ ] Create test reproducing the error
- [ ] Fix
- [ ] If relevant [Update Examples and Showcase](https://cookbook.kirby.design/home/showcase/button)
- [ ] Push commits to GitHub
- [ ] Open a pull request (remember to add `closes #issueno` to the description) and ask @kirbydesign/kirby-guild for review
- [ ] Merge to master and delete branch

**Comment by MadsBuchmann** [comment]
We will be moving to Storybook in the future - so it does not make to allocate resources to fix this. 
See: #1316
