### ISSUE TITLE
[BUG] Scrollbar disappears briefly when opening Feature Hint Drawer

### ISSUE THREAD

**Issue by RasmusKjeldgaard** [kirbydesign/designsystem#1505]
**Describe the bug**
There is a brief flicker when opening the custom drawer, because the scrollbar disappears very briefly before being added back again.

**To Reproduce**

1. Go to https://cookbook.kirby.design/home/showcase/modal
2. Click on 'Interact with background (drawer only)'
3. Open drawer
4. See brief flicker when scrollbar is removed and added back

**Kirby version**
- 1.5.3

**Expected behavior**

**Screenshots**

**Please complete the following information:**
- OS: [e.g. Windows, MacOS, iOS]
- Browser [e.g. Chrome, Safari]
- Browser version [e.g. 22]

**Additional context**

## Tasks:
- [x] Have the bug report verified by contacting a member of @kirbydesign/kirby-guild
- [ ] Move issue from "Ready to do" -> "in progress" on our [project board](https://github.com/kirbydesign/designsystem/projects/1)
- [ ] Create Fix Branch
- [ ] Create test reproducing the error
- [ ] Fix
- [ ] If relevant [Update Examples and Showcase](https://cookbook.kirby.design/home/showcase/button)
- [ ] Push commits to GitHub
- [ ] Open a pull request (remember to add `closes #issueno` to the description) and ask @kirbydesign/kirby-guild for review
- [ ] Merge to master and delete branch
