### ISSUE TITLE
[TRACKING] Accessibility

### ISSUE THREAD

**Issue by alxzak** [kirbydesign/designsystem#1522]
**Describe the solution you'd like**
A tracking Issue for all issues relating to keyboard navigation, tabs, inserting, selecting etc. 

All user interface components and navigation must be [operable](https://www.w3.org/TR/WCAG21/#operable) and meet the success criteria for [Keyboard Accessible](https://www.w3.org/TR/WCAG21/#keyboard-accessible) to _make all functionality available from a keyboard_ and the success criteria for [Navigable](https://www.w3.org/TR/WCAG21/#keyboard-accessible) guidelines to _provide ways to help users navigate, find content, and determine where they are_. There may be other WCAG principles that apply to this issue.

The success criteria must be met where it makes sense on a component level, i.e., they must be met within every component. It is up to the applications that use Kirby components to ensure overall WCAG 2.1 compliance. Therefore, the Kirby components must not prevent that host applications can adhere to accessibility requirements.

Aim for WCAG 2.1 level AA (including level A) compliance.

**Resources**

- [Web Content Accessibility Guidelines (WCAG) 2.1](https://www.w3.org/TR/WCAG21/) - in particular the _Keyboard Accessible_ and _Navigable_ sections.
- WebAIM [Keyboard Accessibility](https://webaim.org/techniques/keyboard/)

Also see the _How to meet_ and _Understanding_ documents for each success criterion in WCAG, e.g., [How to meet Keyboard](https://www.w3.org/WAI/WCAG21/quickref/#keyboard-accessible) and [Understanding Keyboard](https://www.w3.org/WAI/WCAG21/Understanding/keyboard.html).

## Issues

- [ ] [Identify pain points and prioritize](1587)
- [ ] [Create process for performing accessibility evaluation](1589)
    - Automated testing
    - Manual user testing
    - Decide when to do accessibility audits in the future, e.g., when introducing new components and when modifying existing components
- [ ] [Perform accessibility audit on all Kirby components](1588)
- [ ] [TBD] Create actionable issues for ensuring WCAG 2.1 compliance in Kirby components

### Kick Off:

- [ ] Go through all components and test if keyboard is supported. 
- [ ] Create issues for every task, linking to this tracking issue

:tada: Celebrate
