### ISSUE TITLE
[Enhancement] Remove Highchart Charts

### ISSUE THREAD

**Issue by MadsBuchmann** [kirbydesign/designsystem#1578]
**Please add a short description of your enhancement request**
Once #1652 has been carried out and we know when to finally remove the old chart components - _all_ of the old chart components should be removed. 

### Todo: 
- [x] Remove the `kirby-chart-deprecated` component 
- [x] Remove the `kirby-stock-chart-deprecated` component
- [x] Remove associated cookbook pages for both 
- [x] Remove any & all dependencies to highcharts in package.json files! 
- [ ] Ship it & celebrate with colleagues in close proximity! 🚣💨🕺💃

**Additional context**
This is part of an epic - please have a look at it: #1413 
Also #1652 should be carried out before this task.

**Comment by MadsBuchmann** [comment]
Also remember to remove the Stock Chart component: https://cookbook.kirby.design/home/showcase/stock-chart 

It is not in use by any consumer projects and can safely be removed ☄️

**Comment by MadsBuchmann** [comment]
@alxzak This is ready to go. Perhaps a candidate for the next major version?

**Comment by MadsBuchmann** [comment]
Scheduled for v7; a branch exists where highcharts and the components has been removed https://github.com/kirbydesign/designsystem/tree/enhancement/1578-remove-highchart-charts

Remember to rebase it once it's actually going to be used :-)

**Comment by alxzak** [comment]
Target Kirby version 7

**Comment by jkaltoft** [comment]
We need a PR for https://github.com/kirbydesign/designsystem/tree/enhancement/1578-remove-highchart-charts.
Consider creating a new base branch for release v7
