### ISSUE TITLE
[BUG] Numeric Inputmask shows a zero when all digits are deleted

### ISSUE THREAD

**Issue by RasmusKjeldgaard** [kirbydesign/designsystem#1619]
**Describe the bug**

Numeric Input mask placeholder is 0 as default. This means that if a user enters one or more digits in the input field, and subsequently deletes all digits again, a 0 will remain.

When focus is removed from the input field, the 0 will also disappear. 

**To Reproduce**

1. Go to 'https://cookbook.kirby.design/home/showcase/form-field'
2. Scroll down to 'Decimal mask'
3. Enter a number in the input field, and delete it again
4. See a `0` in the input field
5. Click outside input field
6. See an empty input field without a `0`

**Kirby version**
- 1.5.9 (decimal mask introduced) up until current (2.0.8)

**Expected behavior**
I expect that the input field is empty (or shows the placeholder of the input field) when I delete the final digit in the input. 

## Tasks:
- [x] Have the bug report verified by contacting a member of @kirbydesign/kirby-guild
- [x] Move issue from "Ready to do" -> "in progress" on our [project board](https://github.com/kirbydesign/designsystem/projects/1)
- [ ] Create Fix Branch
- [ ] Create test reproducing the error
- [ ] Fix
- [ ] If relevant [Update Examples and Showcase](https://cookbook.kirby.design/home/showcase/button)
- [ ] Push commits to GitHub
- [ ] Open a pull request (remember to add `closes #issueno` to the description) and ask @kirbydesign/kirby-guild for review
- [ ] Merge to master and delete branch
