### ISSUE TITLE
[TRACKING] Migrate Line chart to ChartJS

### ISSUE THREAD

**Issue by alxzak** [kirbydesign/designsystem#1627]
It should be possible to create line charts using the chart component. 

It has been decided to do this in five steps: 
- [x] #1727
- [x] #1732  
- [x] #1729
- [x] We should create an example for the cookbook implementing the requested design
- [x] #1728

### Kick Off:

- [ ] Ensure the enhancement is `UX refined` and aligned with UX 
_The component and/or enhancement should be published and available in the [Kirby Styleguide on Zeplin](https://zpl.io/258pXGj)_
- [ ] Ensure the enhancement has been `Tech refined` with @kirbydesign/kirby-guild and this issue is updated with a clear implementation description  
_This issue should be in the [Ready to do](https://github.com/kirbydesign/designsystem/projects/1#column-4590936) column of the [Kirby kan-ban board](https://github.com/kirbydesign/designsystem/projects/1) before starting implementation)_
- [ ] Assign yourself to this issue and move it to the [In progress](https://github.com/kirbydesign/designsystem/projects/1#column-4590937) column of the [Kirby kan-ban board](https://github.com/kirbydesign/designsystem/projects/1)

### Code:

- [ ] Create Feature Branch from [master branch](https://github.com/kirbydesign/designsystem/tree/master)
- [ ] Create a draft implementation and push to Github
- [ ] Ask a member of @kirbydesign/kirby-guild for a WIP review by creating a draft Pull Request
- [ ] Implement unit tests
- [ ] Update Cookbook Examples and Showcase, i.e. see [Radio](https://cookbook.kirby.design/home/showcase/radio)  
_Also remember to add any relevant new API documentation_

### Review:

- UX review:
  - [ ] Ensure implementation is correct in relation to the UX design and the [Kirby Styleguide on Zeplin](https://zpl.io/258pXGj)
  - [ ] With UX agree on the version of the implementation
- Code review:
  - [ ] Open a pull request (or mark the existing draft PR as `Ready for review`) and ask @kirbydesign/kirby-guild for a review  
_Remember to add `closes #issueno` to the description of the PR._
  - [ ] Once approved, merge feature branch/PR to master
- [ ] Ask a member of @kirbydesign/kirby-guild to add a link to component showcase from Kirby Component Status and update the version number

:tada: Celebrate

**Comment by alxzak** [comment]
https://app.zeplin.io/project/5f50bcf068aedf4f1f010beb/screen/5fa15a50a83ce2818520a9ec
![image.png](https://images.zenhubusercontent.com/602ac85e6b87087753686a4f/c8bd1e34-d38b-4ed4-827b-7368a2595a3c)

**Comment by henrikvoetmand** [comment]
Screens from Investment:
![Graf-landscape](https://user-images.githubusercontent.com/71710012/131475849-2b4be5b1-5026-478a-9bc7-a3ab2df7330d.png)
![Graf-portrait](https://user-images.githubusercontent.com/71710012/131475855-2d4aee53-d284-4514-a881-22076d289cde.png)

**Comment by MadsBuchmann** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Zenhub-602b70d809e4aa00141a1a93/issues/kirbydesign/designsystem/1627?planning-poker) with ZenHub @jkaltoft @RasmusKjeldgaard

**Comment by MadsBuchmann** [comment]
@alxzak I've taken the liberty of splitting this up into three separate tasks. See the issue description.

**Comment by troelslenda** [comment]
In order not to stall the 3.x upgrade of Kirby in our project I came up with the following settings that was necessary to resemble the previous graph that was using chartjs 2.x.

```typescript
const customOptions: ChartOptions = {
      responsive: true,
      maintainAspectRatio: false,
      animation: {
        duration: 0,
      },
      layout: {
        padding: {
          left: 0,
          right: 0,
          top: 30,
          bottom: 0,
        },
      },
      scales: {
        x: {
          type: 'time',
          time: {
            unit: 'year',
            displayFormats: {
              hour: 'HH',
              day: 'D MMM',
            },
          },

          grid: {
            lineWidth: 0,
          },
          ticks: {
            maxRotation: 0,
            autoSkipPadding: 40,
            color: this.colorFont,
            font: {
              size: 11,
            },
          },
        },
        y: {
          display: true,
          grid: {
            drawBorder: false,
          },
          ticks: {
            stepSize: steps.step,
            display: true,
            color: this.colorFont,
            font: {
              size: 11,
            },
          },
        },
      },
      elements: {
        line: {
          tension: 0, // Smooth curve (0 = no smoothing)
          borderWidth: 2,
          borderColor: this.colorGraph,
        },

        point: {
          radius: 0, // By default points are hidden (if 0)
          hoverRadius: 8,
          hoverBorderWidth: 0,
          hoverBackgroundColor: this.colorPoint,
        },
      },

      normalized: true,
      hover: {
        mode: 'index',
        intersect: false,
      },
      plugins: {
        tooltip: {
          // Hover labels,
          mode: 'index',
          intersect: false,

          caretSize: 0,
          caretPadding: 12,
          cornerRadius: 2,
          displayColors: false,
          backgroundColor: this.colorTooltip,
          padding: 8,
          titleColor: this.colorGraph,
          titleFont: {
            weight: 'normal',
            size: 12,
          },
          bodyColor: this.colorGraph,
          bodyFont: {
            size: 15,
            weight: 'bold',
          },
          callbacks: {
            title: (context): string =>
              moment(context[0].parsed.x)
                .tz(TimeOrDatePipe.DK_TZ)
                .format(chartTimeFormats.tooltipFormat),
            label: (context): string =>
              formatNumber(context.parsed.y, this.locale, '1.2-2'),
          },
        },
        datalabels: {
          // min and max labels.
          backgroundColor: this.colorGraph,
          color: this.colorDatalabelsFont,
          borderRadius: 3,
          font: {
            lineHeight: 1,
            size: 11,
          },
          padding: {
            top: 6,
            left: 5,
            right: 5,
            bottom: 5,
          },
          offset: 5,
          align: (context: Context): Align => {
            const currVal: Point = this.getChartPointFromContext(context);
            return currVal !== null
              ? this.max === currVal.y
                ? 'top'
                : 'bottom'
              : null;
          },
          display: (context: Context): boolean => {
            return (
              context.dataIndex === minIndex || context.dataIndex === maxIndex
            );
          },
          formatter: (value: any, context: Context): string => {
            const currVal: Point = this.getChartPointFromContext(context);
            return currVal !== null
              ? formatNumber(currVal.y as number, this.locale, '1.2-2')
              : null;
          },
        },
      },
    };

    const config: ChartConfiguration = {
      type: 'line',
      data: {
        datasets: [
          {
            data: data,
          },
        ],
      },
      options: merge(customOptions, overrideOptions),
    };
```
![image](https://user-images.githubusercontent.com/263060/131998949-162baa5b-614c-47b9-8566-2ae89fb7711d.png)
I believe that this setup would be usable representing one or more securities.

**Comment by MadsBuchmann** [comment]
@henrikvoetmand @troelslenda @bdytos @alxzak 

To avoid confusion I just wanted to align expectations to what is being merged with #1737 which solves #1727. 

It is not a fully fledged stock chart as can be seen I the comment from @troelslenda or @henrikvoetmand. Neither is it the ability to make a chart with labels, custom borders & marked areas as can be seen in the comment from @alxzak. 

 It is a super basic line chart which makes it possible to draw one or more lines with labels along the axis. In order to be able to get it to a point as can be seen on the images, further work has to be done. See the linked tasks from the issue description.

**Comment by troelslenda** [comment]
> @henrikvoetmand @troelslenda @bdytos @alxzak
> 
> To avoid confusion I just wanted to align expectations to what is being merged with #1737 which solves #1727.
> 
> It is not a fully fledged stock chart as can be seen I the comment from @troelslenda or @henrikvoetmand. Neither is it the ability to make a chart with labels, custom borders & marked areas as can be seen in the comment from @alxzak.
> 
> It is a super basic line chart which makes it possible to draw one or more lines with labels along the x-axis. In order to be able to get it to a point as can be seen on the images, further work has to be done. See the linked tasks from the issue description.
> 
> The reason it has taken some time to resolve #1727 is that some refactors had to be made. There are more details on the PR #1737.

We are not in a hurry since we rely on our own implementation of chartjs. In my team we have an issue in our backlog regarding the migration from this custom chart to a `kirby-chart` as soon as it's ready.
Is the plan to provide stock like chart's with https://github.com/kirbydesign/designsystem/issues/1728? I've discussed it with @askarby and we propose that a stock chart is rather fixed with a minimal of options/settings required in order to ensure a uniform presentation throughout the application.

**Comment by RasmusKjeldgaard** [comment]
Closing this as line chart is migrated to ChartJS! 📈
