### ISSUE TITLE
[BUG] Buttons with a "condition" are displayed with wrong text color (iOS 14.6)

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#1628]
**Describe the bug**
Buttons with a condition have the wrong text color (semi-dark)

**To Reproduce**
Steps to reproduce the behavior: Can only be teste on a native device, in something like DRB.

1. Go to Settings
2. Click on Profile / Email
3. Change email

**Kirby version**
v2.0.9

**Expected behavior**
Should be black text

**Screenshots**
![Skærmbillede 2021-06-16 kl  09 29 05](https://user-images.githubusercontent.com/49033002/122176899-6414f780-ce85-11eb-949e-426c84c49778.png)

**Please complete the following information:**
- OS: iOS14

## Tasks:
- [x] Have the bug report verified by contacting a member of @kirbydesign/kirby-guild
- [x] Move issue from "Ready to do" -> "in progress" on our [project board](https://github.com/kirbydesign/designsystem/projects/1)
- [x] Create Fix Branch
- [ ] Create test reproducing the error
- [ ] Fix
- [ ] If relevant [Update Examples and Showcase](https://cookbook.kirby.design/home/showcase/button)
- [ ] Push commits to GitHub
- [ ] Open a pull request (remember to add `closes #issueno` to the description) and ask @kirbydesign/kirby-guild for review
- [ ] Merge to master and delete branch

**Comment by MadsBuchmann** [comment]
Bug has been verified - also happens on an iPad Air 3 running iPadOS 14.6.

**Comment by MadsBuchmann** [comment]
Might be related to this issue: https://github.com/mui-org/material-ui/issues/26251 
(there is also mentions of ionic in the comments)

**Comment by MadsBuchmann** [comment]
After investigating this bug for a while it seems as if this issue stems from a bug in Safari shippied with iPadOS & iOS 14.6. 

### Findings
The correct property & and styles are actually applied - and if the computed properties are inspected it is also visible that the correct color is computed. But for some reason the text is not rendered with it. 

If the text is forced to be re-rendered either by changing the text through inspector tools or by changing the value of the text programatically (see very poor work around below) - it will have the correct color applied. 

I've played around with workarounds mentioned in the aforementioned issues but can't get any of them to work satisfactorily. 

### Very Poor Workaround
The closest I've come to a solution Is to use a `Timeout` to very quickly swap the text in and out again to force a rerender. This unfortunately results in the transition effect not being applied. 

```typescript
  disabled = false;
  _buttonText = `${this.disabled}`;
  onClick() {
    this.disabled = !this.disabled;

    setTimeout(() => {
      const oldValue = this._text;
      this._text = '';

      setTimeout(() => {
        this._text = oldValue;
      }, 1);
    }, 1);
  }

```

### Conclusion 
I am quite confident that we're experiencing the same bug as the two issues above refer to - as they also have the issue of the correct property value actually being computed but not rendered. 

Therefore I think we should do as material-ui & simply close this issue as it will be fixed with [iOS 14.7](https://github.com/mui-org/material-ui/issues/26251#issuecomment-871254568).

**Comment by MadsBuchmann** [comment]
14.7 is released and it seems to have fixed the problem 😄
