### ISSUE TITLE
[Housekeeping] Create publish workflow for web-component core lib

### ISSUE THREAD

**Issue by RasmusKjeldgaard** [kirbydesign/designsystem#1630]
**Short description of housekeeping request**
Based on the badge web component in #1315, we need to create a publishing workflow for our new core package.  

N.B. With the new library structure, we have moved the scss files, and thus need to adjust the publish scripts lib folder path, used here: https://github.com/kirbydesign/designsystem/blob/master/scripts/publish.js#L114-L124

To preserve backwards compatability, we still need scss utils etc. to be available under @kirbydesign/designsystem. 

**Alternatives**
N/A. 

**TODO**
- [x] Publish existing `designsystem` library, where badge is now a web component with an Angular Proxy. 
- [x] Verify it works in e.g. DRB. 
- [x] Create publishing workflow for `core` library package (with separate package on npm as result)
- [ ] Verify it works in e.g. vanilla js project or with a consumer project (hjemmesideteamet/WCM?)
- [ ] Ensure that version changes to core package results in a version pump (and new publish) for angular components

**Additional context**
### Kick Off

* [ ] Ensure this issue has been `Tech refined` with @kirbydesign/kirby-guild and is updated with a clear implementation description
  _This issue should be in the [Ready to do](https://github.com/kirbydesign/designsystem/projects/1#column-4590936) column of the [Kirby kan-ban board](https://github.com/kirbydesign/designsystem/projects/1) before starting implementation_
* [ ] Assign yourself to this issue and move it to the [In progress](https://github.com/kirbydesign/designsystem/projects/1#column-4590937) column of the [Kirby kan-ban board](https://github.com/kirbydesign/designsystem/projects/1)

### Code Review

* [ ] Open a pull request (or mark the existing draft PR as `Ready for review`) and ask @kirbydesign/kirby-guild for a review
  _Remember to add `closes #issueno` to the description of the PR._
* [ ] Once approved, merge feature branch/PR to master

:tada: Celebrate

**Comment by RasmusKjeldgaard** [comment]
Stencil publishing guidelines: https://stenciljs.com/docs/publishing

Also remember to consider which strategy to use for bundling/output targets: https://stenciljs.com/docs/output-targets

**Comment by RasmusKjeldgaard** [comment]
Verification:
- [ ] `npm pack` core lib locally, so we get a .tgz file
- [ ] install in cookbook, by replacing file link in package with .tgz package
- [ ] use existing publish script, but adjust so angular libs package.json points to .tgz file and install to DRB to verify 
- [ ] Publish core package to npm
- [ ] change angular libs package.json back to point to v0.0.1, which is now live
- [ ] install .tgz of angular lib on drb branch again to verify and test with DRB people
- [ ] merge and celebrate 🍾
