### ISSUE TITLE
[Housekeeping] Deprecate Highcharts Charts & Ship Chart.js Charts

### ISSUE THREAD

**Issue by MadsBuchmann** [kirbydesign/designsystem#1652]
- [X] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the housekeeping request

When the following two issues has been completed & is ready for release: #1574 #1572 - then the old highcharts charts should be deprecated. 

The deprecation should happen by suffixing current selectors for the Highchart charts  with `-deprecated`. Likewise the selectors for the new Chart.js charts should have removed the `-wip` suffix from their names. 

This means when consumer projects bump to the version of Kirby where the deprecated charts are included; all they have to do is suffix their charts with `-deprecated`. 

### TODO: 
- [x] Inform stakeholders that this is happening!
- [x] Rename the current `kirby-chart` component to `kirby-chart-deprecated` 
- [ ] Rename the current `kirby-stock-chart` component to `kirby-stock-chart-deprecated` 
- [x] Rename `kirby-chart-wip` component, related types & services to not include the `-wip` suffix. 
- [x] Update the cookbook page to reflect that these two components are now deprecated
- [ ] Find a deadline for #1578 

## Have you considered any alternatives?
Remove the old Highcharts charts in a "Big Bang"-manner and stress consumer projects to use the new Chart.js charts. But that is not very thoughtful :-)
