### ISSUE TITLE
[Enhancement] Install and setup @storybook/angular in repository

### ISSUE THREAD

**Issue by RasmusKjeldgaard** [kirbydesign/designsystem#1824]
- [x] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the enhancement
Based on the [enhancement/web-components](https://github.com/kirbydesign/designsystem/tree/enhancement/web-components) branch, we should install and setup the angular version of Storybook.

This way, we can base the first story on the badge web component, and check that it will work with the proxies-file.

## Describe the solution you'd like
We should simply install the npm package and create a config for storybook, alongside a first documentation page.

It should support [writing stories in MDX](https://storybook.js.org/docs/react/writing-docs/mdx) (as opposed to the generic auto-generated docs page), and have a controls for the component in an API Prop table on the docs page.  

## Have you considered any alternatives?
We should research http://bit.dev in parallel to make an informed decision!

## Are there any additional context?

<hr />

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/master/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Refinement

- [ ] Request that the issue is [UX refined](https://github.com/kirbydesign/designsystem/blob/master/.github/CONTRIBUTING.md/#ux-refinement); do not proceed until this is done.
- [ ] Request that the issue is [tech refined](https://github.com/kirbydesign/designsystem/blob/master/.github/CONTRIBUTING.md/#tech-refinement); do not proceed until this is done.

### Implementation 
The contributor who wants to implement this issue should: 

- [ ] Make sure you have read: "[Before you get coding](https://github.com/kirbydesign/designsystem/blob/master/.github/CONTRIBUTING.md/#before-you-get-coding)".
- [ ] Signal to others you are working on the issue by assigning yourself.
- [ ] Create a branch from the [master branch](https://github.com/kirbydesign/designsystem/tree/master) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Publish a WIP implementation to Github as a draft PR and ask for feedback. 
- [ ] Make sure you have implemented tests following the guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)".
- [ ] Update the [cookbook](https://cookbook.kirby.design) with examples and showcases.

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request. If you created a draft PR during implementation you can just mark that as "ready for review".

**Comment by MadsBuchmann** [comment]
Part of tracking #2011. Removing stale label.
