### ISSUE TITLE
[RESEARCH] Desktop ready general solution for hover state 

### ISSUE THREAD

**Issue by RasmusKjeldgaard** [kirbydesign/designsystem#1866]
## Describe why and what should be researched
As part of the work of making the Kirby Components Desktop Ready, it would make sense to research if it is possible to make general solutions for various interactivity states, before beginning implementing component specific solutions. This issue is concerned with hover/cursor (pointer/hand/mickey-mouse-thingy). 

## Considerations 
The following is worth considering when researching
### Design: 
- [ ] Background color?
- [ ] Border?
- [ ] Shadow?

### Implementation: 
- [ ] Investigate differences between components, to see if we can make a generalized solution. 
- [ ] Prioritise general solution in html and css (directives will have to be rewritten later when moving to web-components)
- [ ] `cursor: pointer` is part of this solution, make sure to set this on the element. 

### Other
- [ ] No

## Describe the goal
To unearth problems and consider if it is possible to come up with a (potentially partially) general solution for implementing the interactivity state. If possible also a POC of the solution.

**Comment by MadsBuchmann** [comment]
Timebox: 3 days

**Comment by jkaltoft** [comment]
# 💡 Findings

* The `hover()` mixin is the only place we use `:hover { ... }`, except
    * Calendar:
        * `.day.selectable:not(.selected):hover { ... }`
        * Cookbook specific styles
* We only utilize the `hover()` mixin in two places:
    * Button
    * Chip

**Comment by jkaltoft** [comment]
# 📝 Tasks

## Refactor usage of `hover()` mixin - use `apply-hover()`

1. Create new utility/mixin `apply-hover()`
1. Refactor components - use `apply-hover()`
     - Button
     - Chip
1. Look for other components where we _should_ use `apply-hover()`
1. Consider removing `hover()` mixin completely 

This may require decomposition of hover as a concept, e.g. into:

- Cursor
- Elevation
    - Background
    - Border
    - Box shadow
- Typography
    - Text color
    - Text weight (bold, light etc.)
- Opacity/transparency
- Translation (positioning)
- Transition/animation
- Tactility (probably not)
- Audio (probably not)
