### ISSUE TITLE
[TRACKING] Desktop ready Button

### ISSUE THREAD

**Issue by RasmusKjeldgaard** [kirbydesign/designsystem#1869]
- [x] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

### Todo

Make button great again! We should make sure our button component adheres to our desktop definition of done, outlined in the following.

#### Design
- [x] Redesign focus outline (offset, thickness, color)
- [x] Differentiate hover and pressed colors

#### Implementation

Make sure following functionality works (if applicable) according to respective issue:
- [x] Touch
    - [x] Pressed
      - #1867
- [x] Mouse
    - [x] Hover
      - #1866
      - #1935
      - #2007 
    - [x] Pressed
      - #1867
    - [x] Hand
      - #1866
- [x] Keyboard
    - [x] Focus
      - #1863
    - [x] Enter/Space
      - #1868 **NB: currently enter does not change colors for pressed state**
- [x] State 
    - [ ] Active
    - [ ] Disabled - research if disabled state should be focusable (should work as you would expect a native button)

**Comment by RasmusKjeldgaard** [comment]
Remember to fix #1512 when we are working on button.

**Comment by RasmusKjeldgaard** [comment]
And we should seriously consider to move this to a web component now, before introducing these improvements!
