### ISSUE TITLE
[TRACKING] Cookbook Improvements

### ISSUE THREAD

**Issue by jakobe** [kirbydesign/designsystem#188]
This issue is to track ideas and tasks for improving the cookbook.

### General:
- [ ] Add Component Overview
  - [ ] Create Component Icons for Cookbook: #179 
  - [ ] Add Icons to side menu items
  - [ ] Create Component Overview page a la https://ionicframework.com/docs/components/
- [x] Add link to https://kirby.design/
- [ ] Write general description of "what the cookbook is" (and isn't) - that it's limited to Angular, etc. 
- [x] Add more prominente link to Github (in navigation bar), so that it's not only accessible from Component showcase sub-pages, or Component-status page. 
- [x] Redesign header: #1308
- [ ] Add "How to Contribute" section: #1373 
- [x] Add contribution guidelines to repo: #1393

### Refactorings:
- [ ] Move examples to be sub-"things" of Showcases (1 showcase - 1:N examples)

### Component Status:
- [x] Fetch New Component Requests from GitHub API
- [ ] Enhancements and versioning:
  - [x] Fetch Component Enhancement Requests from GitHub API
  - [x] Show Component Enhancement Requests together/under `Ready` status
  - [ ] Handle Component Versioning:
    - [ ] E.g. `package.json` file inside each component folder + `npm version [<newversion> | major | minor | patch]`?
- [ ] Make Responsive

### Showcase:
- [ ] Multiple examples on a single showcase (dropdown)
- [ ] Auto-generate API documentation using https://typedoc.org/
  - [ ] Move API documentation to code annotations
  - [ ] Auto-generate API documentation to `json` file 
  - [ ] Render API documentation from `json` file in each component showcase
  - Interactive Properties
    - [ ] Setup "Interactive" Properties - with manual setup of values
    - [ ] Generate "Interactive" Properties from `json` api file
    - [ ] Predefined datasets + manual data blob
- [ ] Add segments for:
  - [ ] `.scss` (when relevant - decorator on example?)
  - [ ] `.ts` (when relevant - decorator on example?)
  - [ ] `.tns.html` (if "the same", omit .tns.html)
- [ ] Wrap components in resizable container to show responsiveness of components a la https://polaris.shopify.com/components/structure/callout-card
- [ ] Split examples into subpages/areas on the Component Page a la https://polaris.shopify.com/components/actions/button
- [ ] Display (screenshots) of what the various Components looks like, natively rendered
- [ ] Link to Component source (on Github)

**Comment by alxzak** [comment]
We will migrate from cookbook to storybook later this year.

This issue will be closed due to backlog prioritization and pruning.
https://github.com/kirbydesign/designsystem/discussions/1704#discussion-3522993
