### ISSUE TITLE
[TRACKING] Nativescript issues

### ISSUE THREAD

**Issue by jonasjensen-brolstark** [kirbydesign/designsystem#204]
### List:
- [ ] [iOS: listview footer is shown in every group when grouping enabled](https://github.com/telerik/nativescript-ui-feedback/issues/951)
- [ ] [iOS: Missing listview header when grouping is enabled](https://github.com/telerik/nativescript-ui-feedback/issues/950)
- [ ] [Section sort order](#114)
- [ ] How to build a reusable list component with flexible item template(s) without nesting layout containers

### Keyboard / Inputs
- [ ] Inputs with error messages underneath (keyboard overlays, so you can't see the error message, primarily an issue on android even with "autopan" configured.
- [ ] Floating buttons which is moved up when the keyboard is opened? 

### Styling
- [ ] iOS: using a `[ngClass]`-binding on eg. RadListView, with values derived form other bindings, does not update after initial render. (for further details, ask: @askarby)
- [ ] Using `:host`-selector for styling a Component, only renders it once, then goes back to default styling for consequtive renderings / components.

## Long term wishlist
... of things that would make {N} just a bit more awesome to work with:
- [ ] Add support for pseudo selectors (in css) - candidates would be `:first-child`, `:last-child`, `:first-of-type`, `:last-of-type`, `:nth-child`etc.
- [ ] Automatically register all `@Components` with {N}, that are declared in `@NgModule`s, to avoid having to create a `.tns.ts`-component and manually registering it (eg.: `registerElement('...component selector...', () => require('...path-to-component...').MyComponent);`

**Comment by jonasjensen-brolstark** [comment]
The two bugs, [iOS: listview footer is shown in every group when grouping enabled](https://github.com/telerik/nativescript-ui-feedback/issues/951) and [iOS: Missing listview header when grouping is enabled](https://github.com/telerik/nativescript-ui-feedback/issues/950), seems to be fixed. 

This needs to be tested but would be awesome if they are fixed.

**Comment by johan-mjolner** [comment]
My list of suggestions for discussion with Progress:

- Suggestions for how to combine a tabview and a side-drawer – can we use the NativeSccript TabView?
- How can we have a header the “Apple” way: Scrolling the big title away causes the navigation bar to appear
- Tap twice on tab -> go to first page of tab
- Improvements to the compilation speed and the auto-refresh feature (problems when changing routes(?))
- Help with specific but on team1: `CONSOLE LOG file:///app/vendor.js:91664:20: NavigationError(id: 6, url: '/tabs/(dashboardTabOutlet:dashboardTab//inboxTabOutlet:inboxTab)', error: TypeError: null is not an object (evaluating 'this._ios.controller.delegate = null'))`. Occurs only on staging, not on mock.

**Comment by langecode** [comment]
One point regarding builds. We have had to edit `webpack.config.js` to support multiple environment configuration the same way Angular does. Would be nice to have a way to set the "Angular" configuration instead of having to redo the file substitution in the webpack configuration.

**Comment by labanos** [comment]
N R.I.P

**Comment by diegovincent** [comment]
Any news?
