### ISSUE TITLE
[Enhancement] Align modal & page margins with sketch

### ISSUE THREAD

**Issue by MadsBuchmann** [kirbydesign/designsystem#2232]
- [X] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the enhancement
The page & modal both have a padding of 16 pixels - but it should actually be 32 pixels as defined in sketch; it's a disperance. 

In DRB this has been mitigated by overriding it in the consumer project. 

In our cookbook we can actually see the disperance on the page showcase. Notice how the title has 32 pixels padding and the paragraphs below it has 16px. : 
![Screenshot 2022-05-05 at 14 06 50](https://user-images.githubusercontent.com/17269698/166919758-08c32d43-ac26-4c4e-a6ca-91e2754d61bd.png)

The reason for the padding being 16px is that some elements such as the [form field](https://cookbook.kirby.design/#/home/showcase/form-field) should have a padding of 16 px. The caret inside the input should however have 32 px, aligning with the body text. 

How do we fix this? (I know that Mr. Css himself has some thoughts regarding a solution @jkaltoft)

## TODO: 
- [ ] Fix issue for page 
- [ ] Fix issue for modal
