### ISSUE TITLE
Component walkthrough

### ISSUE THREAD

**Issue by MadsBuchmann** [kirbydesign/designsystem#2329]
# Components 

## Accordion 
- [x] #2339

## Action sheet 
- [ ] Use pressed/hover state styles for focus when tabbing (#2236 might solve this) 
- [x] #2340
- [ ] It is possible to spam open to get like a bazillion action sheets 
- [ ] #404 should be solved

## Alert 
- [ ] The alert shouldn't slide in from the bottom *on desktop* - but appear in the middle of the screen... Somehow, more design needed. On mobile it should still appear from bottom

## Button 
 Looks good! 

## Calendar 
- [ ] Look into swapping out with new datetime component from ionic 6. The year selector experience might be a bit iffy on desktop as it uses a native like selector.

## Checkbox 
- [ ] we could consider creating some sort of "checkbox-group" component to semantically tie the checkboxes together. Might be more accessibility releated. 

## Chip 
- [x] #2341

## Dropdown 
-  [x] #2342

## FAB Sheet
... Should generally not be used on desktop. It is a mobile pattern. 
- [ ] Write guidelines in the cookbook that it should not be used on desktop 

## Item Picker 
- [ ] No styles on tab navigation: should only change background color - no focus ring. #2236 is once again relevant. 

## List Component 
- [x] #2343

## Modal 
-  It does not recieve focus when it opens. If you use only keyboard it's impossible to navigate the modal. But consumers can programatically set focus inside if necessary. - Solved via Ionic 6 upgrade!! ~~~~~ dance dance dance ~~~~~ 

 

## Range 
- [ ] (nice to have) Has no label showing value when using keyboard. Might be more of an accessibility thing. 

## Reorder list 
- [x] #2344
- [ ] It is not possible to reorder using keyboard. Might be more of an accessibility thing tho. 

## Segmented Control 
- [x] #2345
- [x] #2346
- [x] #2347
- [ ] #2348
- [x] #2349

## Slide 
- [ ] Deprecate it, it will be removed in ionic v7. See: #1986 

## tabs
- [ ] tabs does not load until pressed the second time. Might be related to onPush. Might just be a cookbook issue 🤷  
- [ ] The menu button does not react on space and enter 
- [ ] Totally lacks interaction states 

## Toggle button 
- [ ] Rewrite toggle button to stateful button. Right now we're swapping it out and this removes the focus.
