### ISSUE TITLE
[Enhancement] Modal Finalization Epic

### ISSUE THREAD

**Issue by RasmusKjeldgaard** [kirbydesign/designsystem#2974]
- [x] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the enhancement
This epic is a list of known issues with modal implementation and documentation needed to mature the Modal for production use:

### API issues
- [ ] The default behavior should be to supply a button as trigger-functionality for the inline modal similar to Ionic. 
    - It seems like a code-smell that teams need to maintain an 'open' state for the modal, that they need to set to false when the modal is closed.  
- [ ] `open` should be renamed to `isOpen`
    - and we should describe that this is not the default use case, but developers can take control of the state and e.g. have the inline modal open by default 
- [ ] Content projection should use the kirby-modal-v2-footer instead of an additional attribute with `footer` and possibly also kirby-page-progress instead of `header-start`.

### Implementation/functionality issues
- [ ] ⚠️  Drawer modal is not scrollable on breakpoints below 1.

### Docs
- [ ] Push inline modal for simple use cases - make it more explicit that this is the recommended approach 
- [ ] Make routed modal example use a similar approach to the action group example in the Header cookbook page so it does not jump to the top: https://cookbook.kirby.design/#/home/showcase/header
- [ ] Iphone examples for inline modal and its code snippet should be the same (see e.g. Page Showcase on how to do this)
 
### Migration Notes
- [ ] Describe use of canDismiss and onWillDismiss for returning data from modal
- [ ] Push inline modal for simple use cases
