### ISSUE TITLE
[TRACKING]: Form Field Web Component

### ISSUE THREAD

**Issue by RasmusKjeldgaard** [kirbydesign/designsystem#3353]
- [ ] #3354
- [x] #3355
    - [ ] Map out relevant states
    - [ ] Create test grid with component states
- [ ] #3383
- [ ] DOCUMENTATION: Document Form Field

**Comment by RasmusKjeldgaard** [comment]
Irrelevant as a tracking issue for now, reopen at a later point if necessary
