### ISSUE TITLE
Refactor Button docs

### ISSUE THREAD

**Issue by jakobe** [kirbydesign/designsystem#3637]
As part of preparing for #3638 we should refactor the `Button` docs so we can do Chromatic snapshots before and after the conversion.
To whack two birds with one stone we should also improve the `Button` docs while we're at it 😇  

## Tasks:
- [x] Refactor each `Button` example to it's own component (as we do everywhere else)
- [x] And descriptions for each variant/size/state etc.
- [x] Wrap each example in it's own code viewer
- [x] Add `Button` cookbook example page to Storybook
