### ISSUE TITLE
[TRACKING] Kirby List Features

### ISSUE THREAD

**Issue by dalsgaard** [kirbydesign/designsystem#367]
- [ ] Disable cell - it should be possible to disable a cell - i.e. prevent it from being selected.
- [ ] Selected cell - indication on the selected cell (if any).
- [ ] Cell alerts - a header on the cell indicating a special state.
- [ ] Cells with rounded corners.
- [ ] Collapsible sections - it should be possible to collapse a section, only showing a 'primary' cell.
- [ ] Sticky section headers - it should be possible to make a section header sticky, i.e. showing it as long as it has visible cells.
- [ ] Swipe actions - it should be possible to define swipe actions on cells: #357 
- [ ] Scroll to a specific cell - it should be possible to scroll programatically to a specific cell.
- [ ] Static cells - it should be possible to define static cell content (to solve the scroll-in-scroll problem).
