### ISSUE TITLE
[TRACKING] Input masking

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#937]
This issue is a master issue for input field masking. it has the following granular issues:
- [ ] Date: #1211
- [ ] Phone number: #1212 
- [ ] Numerical and decimal: #1213 

**Is your enhancement request related to a problem? Please describe.**
We would like to be able to separate an input in a field while a user is writing in it, eg. a telephone number or some other information where its visually separated.

![Skærmbillede 2020-03-02 kl  15 22 53](https://user-images.githubusercontent.com/49033002/75685069-445ebd80-5c9a-11ea-81bd-4081a01bb868.png)

**Comment by JoanJensenBD** [comment]
For date input fields we accept the format dd.mm.åååå.
![image](https://user-images.githubusercontent.com/65280082/97876807-a0dc1600-1d1c-11eb-851d-32832f001ce7.png)

- [ ] The placeholder text is 'dd.mm.åååå'
- [ ] The user can only enter numbers
- [ ] '.' is automatically entered/skipped
- [ ] On mobile phones numeric keyboard is displayed.

**Comment by alxzak** [comment]
as all the issues regarding this tracking issue is closed, this will be closed too.
